package Enum;

public enum EnumOutfitters {
    OPEN_WEBSITE,
    NAVIGATE_TO_POPULAR_SECTION,
    CLICK_ON_JACKET,
    VIEW_PRODUCT_DETAILS,
    SELECT_SIZE_XL,
    VIEW_CART,
    VIEW_CART_PAGE,
    CLICK_CHECKOUT,
    ENTER_EMAIL,
    ENTER_FIRST_NAME,
    ENTER_LAST_NAME,
    ENTER_ADDRESS,
    ENTER_CITY,
    ENTER_POSTAL_CODE
}